version: '3.8'

services:
  db:
    image: postgres:alpine
    env_file: .env
    ports:
      - 5432:5432

  init: 
    build:
      context: .
      dockerfile: Dockerfile.init
    env_file: .env
    environment:
      POSTGRES_HOST: db
    depends_on:
      - db

  app: 
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      POSTGRES_HOST: db
    depends_on:
      init:
        condition: service_completed_successfully
    ports:
      - 8080:3000