apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.name" . }}
  labels:
    {{ include "chart.labels" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "app.name" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "app.name" . }}
    spec:
      initContainers:
      - name: "init-{{ include "app.name" . }}"
        image: "ghcr.io/ntnu-ie-iir/tidlig-innsats-ungdom-init:{{ .Values.version }}"
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: {{ include "app.name" . }}
          - secretRef:
              name: {{ include "postgres.name" . }}
        env:
          - name: POSTGRES_DB
            value: {{ include "postgres.database" . }}
          - name: POSTGRES_HOST
            value: {{ include "postgres.name" . }}
          - name: POSTGRES_PORT
            value: {{ include "postgres.port" . | quote }}
          - name: S3_ENDPOINT
            value: {{ .Values.s3endpoint }}
          - name: S3_BUCKET_NAME
            value: {{ .Values.s3bucket }}

      containers:
      - name: {{ include "app.name" . }}
        image: "ghcr.io/ntnu-ie-iir/tidlig-innsats-ungdom-app:{{ .Values.version }}"
        imagePullPolicy: IfNotPresent
        ports: 
        - containerPort: {{ include "app.port" . }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ include "app.port" . }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ include "app.port" . }}
        envFrom:
          - secretRef:
              name: {{ include "app.name" . }}
          - secretRef:
              name: {{ include "postgres.name" . }}
        env:
          - name: NEXTAUTH_URL
            value: {{ printf "https://%s/" .Values.hostname }}
          - name: POSTGRES_DB
            value: {{ include "postgres.database" . }}
          - name: POSTGRES_HOST
            value: {{ include "postgres.name" . }}
          - name: POSTGRES_PORT
            value: {{ include "postgres.port" . | quote }}
          - name: S3_ENDPOINT
            value: {{ .Values.s3endpoint }}
          - name: S3_BUCKET_NAME
            value: {{ .Values.s3bucket }}
