apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.name" . }}
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "app.name" .) ) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $nextAuthSecret := (get $secretData "NEXTAUTH_SECRET") | default (randAlphaNum 48 | b64enc) }}
  NEXTAUTH_SECRET: {{ $nextAuthSecret | quote }}
  S3_ACCESS_KEY: {{ .Values.s3.accessKey | b64enc }}
  S3_SECRET_ACCESS_KEY: {{ .Values.s3.secretAccessKey | b64enc }}
